#alias grep='ack'
alias cs='perl script/*server.pl -d'

platform=`uname`
if [[ $platform == 'Linux' ]]; then
   alias ls='ls -GFA --color=auto'
elif [[ $platform == 'Darwin' ]]; then
   alias ls='ls -GFA'
fi

alias moose='perl -Moose -E'
alias hs="$HOME/.homeshick"
alias pp="prove -lwr t/ | fgrep 'Result:' | xargs -I % $HOME/.workshop/bin/prowl 'Done %'"

# handy aliases for carton
alias ce='carton exec'
function ci { 
    echo "requires q[$1];" >> cpanfile;
    carton install;
}
